### ISSUE TITLE
Getting " One or more errors occurred" while opening GUI

### ISSUE THREAD

**Issue by DoucheHellSung** [javinizer/Javinizer#330]
## Expected Behavior
Ui should have been loaded

## Current Behavior
![image](https://user-images.githubusercontent.com/96594716/159878712-b0f65969-8584-4eda-a224-bc8e111460c3.png)

## Your Environment
* Module version used:2.1.5
* Operating System and PowerShell version:Windows 10 / 7

**Comment by tanpro260196** [comment]
Same error here, this time on both Windows and Linux Docker.

**Comment by punkgamer69** [comment]
Same error here as well, using Windows.

**Comment by endofthescope** [comment]
Hey, wanted to chime in again and say that I got this error again. I was able to fix it without reinstalling by setting the theme to "light" in the jvSettings.json settings file. For some reason it was set to null. I'm assuming since it's set to null it can't choose a theme to go with and gets locked up. Hope this helps.
