### ISSUE TITLE
Cannot install Javinizer GUI - 

### ISSUE THREAD

**Issue by madmax2** [javinizer/Javinizer#344]
## Expected Behavior
Install Javinizer GUI

## Current Behavior
 Error occurred when creating PowerShell Universal directories: Cannot bind argument to parameter 'Path' because it is null.

## Steps to Reproduce (for bugs)
open powershell 7 administrator mode, 

Install the python modules using pip. If running Unix/MacOS, use pip3/python3

> pip install pillow
> pip install googletrans==4.0.0rc1
> pip install google_trans_new

 Install the module from PowerShell gallery

> Install-Module Javinizer

 Check that the module has been installed; if error, restart your console

> Javinizer -v

Version      : 2.5.10
Prerelease   : alpha
Project      : https://github.com/jvlflame/Javinizer
License      : https://github.com/jvlflame/Javinizer/blob/master/LICENSE
ReleaseNotes : https://github.com/jvlflame/Javinizer/blob/master/.github/CHANGELOG.md

Install GUI
>Javinizer -InstallGUI
>Y

Get error 
 Error occurred when creating PowerShell Universal directories: Cannot bind argument to parameter 'Path' because it is null.

## Your Environment
* Module version used: 2.5.10
* Operating System and PowerShell version: Windows 10 , powershell 7

**Comment by amakuramio** [comment]
I have the same problem

**Comment by chronotank79** [comment]
I also have the same issue.

**Comment by nova168168** [comment]
I also have the same issue.

**Comment by SetilaSilvios** [comment]
* I am not a developer nor native English speaker, so what I say can be inaccurate.

It happens when PowerShell fails to load the file directory(=Path) of the 'Javinizer' module.
You might have installed a previous/different version of Powershell (Such as 'Windows PowerShell' from MS Store).
PowerShell 7 can load Modules installed with those different versions, but cannot load its directory with `Get-Installed Module` which is used when installing GUI. 

So before following what I write below, type `Get-Installed Module` in your PowerShell and see wheter 'Javinizer' is in the list.

If not, delete current 'Javinizer'. It has to be done with command `Uninstall-Module Javinizer`, but since PowerShell 7 cannot even recognized that as 'Installed Module' you have to delete it with different version of PowerShell(=what you have previously installed), or just find the folder manually. In my case, it was in `C:\Program Files\WindowsPowerShell\Modules`

Then install Javinizer again, with PowerShell 7. `Install-Moudle Javinizer`.
After that, try `Get-Installed Module` to check if PowerShell can load it properly.

Done. Now install GUI.

+) The new Javinizer module folder might be in `C:\Users\(Username)\Documents\PowerShell\Modules`

**Comment by PriestMarmore** [comment]
One thing I did wrong was installing this with the Windows Powershell instead of Powershell 7, so when I moved to Powershell 7 and tried to install the GUI I couldn't even though I could see my version of javinizer (Javinizer -v). I ended up deleting my files from javinizer (just search on file explorer for Javinizer and open the location of the files and delete them) and doing the process with Powershell 7 from the beginning this time and it worked
