### ISSUE TITLE
Can't move video if download of image fails

### ISSUE THREAD

**Issue by Yukkun** [javinizer/Javinizer#373]
## Expected Behavior
Video file to move even if can't download all images

## Current Behavior
Video does not move to the sort folder if for example the actress image download fails

## Steps to Reproduce (for bugs)
I think this is fairly explanatory but.. 
1. Start sorting your files. I'm using the GUI.
2. Press complete sort for this movie.
3. NFO and images gets downloaded but because some of the actor thumb urls are broken, and does not download, it stops the movie from being sorted to the sort folder.

## Your Environment
* Module version used: 2.5.15, GUI
* Operating System and PowerShell version: Windows 11, PowerShell 7

## Additional info:
I've noticed that this can be sort of bypassed if I just remember to scroll down, click view r18dev data and then press "Replace" for the "Actress"-field. Which is very strange behaviour in general because I'm only using R18dev for scraping anyway.

**Comment by seeyabye** [comment]
Could you give me a video code where this fails? It would speed up my process for debugging.

**Comment by seeyabye** [comment]
What scrapers are you using? ABP-755 should only return one actress for r18 and dmmja at least on my end.

**Comment by seeyabye** [comment]
Could you also share what you have for the metadata priorities (especially for Actress).

**Comment by seeyabye** [comment]
Thanks for provided the requested information.

In the future, it would be better to share the entire `jvSettings.json` instead of images. You can access it by clicking on 'JSON' under the Settings tab.

So apparently you had `scraper.option.addmaleactors` turned checked.

All I can say is that don't scrape for male actors for now. If you must insist on scraping for male actors, I recommend clearing out the jvThumbs.csv for male actors (deleting these lines for now). It seems like when male actors scraping was initially added, the images were hardcoded and stored in jvThumbs.csv, but most of the male actors thumbnail links are broken at this time.

I am still not sure what to do, so I will leave this issue open for now.

**Comment by seeyabye** [comment]
From 2.5.17, Javinizer will ignore thumbnails with invalid links. It will continue to work, but the thumbnails for failed actors/actresses will not be downloaded.
